### ISSUE TITLE
一次拖动多个文件进行还原只能还原选择的第一个文件

### ISSUE THREAD

**Issue by GoudyM** [rippod/apate#8]
请问能不能做到一次还原一整个文件夹的多个文件呢？

**Comment by rippod** [comment]
可以。支持多选拖入，支持文件夹拖入，子目录内的文件也会处理。经测试没有问题。
![PixPin_2024-09-24_23-47-54](https://github.com/user-attachments/assets/5a16adea-feb5-4da1-ac4c-c8e547439428)

**Comment by GoudyM** [comment]
感谢回复，我测试了下，是没有格式的文件会出现这种情况，给文件加上格式就可以批量还原了
