### ISSUE TITLE
无法得知文件被加密了几次，不知文件解密是否真正成功

### ISSUE THREAD

**Issue by PING020903** [rippod/apate#9]
在**老王论坛**里头看到你别人用的软件进行了加密，但是我不知道加密了几次，每次丢进去就是成功，如此两次以后，得到了一个名称无后缀的文件，但是我不知道文件的格式。

我本以为是`.7z`或者`.exe`，但是我去查看了**HEX**发现也不是这两种格式，是一串我看不清端倪的乱码。

建议在加密的时候就给文件填充 *加密次数* 、 *加密方式* 的信息，在解密的时候就根据这些信息来一次性解密，就不需要把文件丢进去解密两次。或者直接把文件头加密了，后面数据是什么也看不出来的，没了文件头，即便就识别不出来这个文件是什么格式。

**Comment by rippod** [comment]
说的有道理，感谢反馈
